// =============================================================
// MCP server.instructions string — attached to every agent's
// system prompt at `initialize` time. Per the MCP protocol, the
// server's `instructions` field reaches the client at the same
// hop as `serverInfo` and is the standard place to put cross-tool
// lifecycle policy that individual tool descriptions can't carry.
//
// History: M3a prompt 1 against voice2work (Codex Desktop) showed
// the agent calling `set_active_topic` and `query_graph` correctly
// but never `emit_node` / `link` after exploring 26 files. Codex
// reasoned: "Codemap doesn't have auth nodes indexed for this
// project, so I'm falling back to a direct repo read." That's the
// "treat-as-cache" failure mode — query miss → explore → done,
// no writeback. This module is the architectural fix:
// inject a lifecycle policy that explicitly demands writeback.
//
// The wording compresses the M1 spike's 3-checkpoint instruction
// doc (m1/instruction-doc.md) to ~180 words — small enough to fit
// the system-prompt budget of every session, prescriptive enough
// to leave no room for the "cache" interpretation.
//
// In v0.2.0 (task-021), the same body is also rendered into
// project-level AGENTS.md / CLAUDE.md files via `codemap init`,
// because Codex Desktop drops `server.instructions` (M3a finding F1).
// Single source of truth — agentsMdContent() reads SERVER_INSTRUCTIONS
// so the in-protocol and in-file copies cannot drift.
// =============================================================

export const SERVER_INSTRUCTIONS = `This server is a persistent knowledge graph of the open codebase
(.codemap/graph.json). Treat it as memory — query before exploring,
WRITE AFTER.

LIFECYCLE for any task that touches this codebase:

1. START: set_active_topic("<short-slug>") — resets per-turn emit budget.
2. BEFORE PLANNING: query_graph("<task description>"). If it returns
   nodes, read via get_node before re-deriving from source.
3. AFTER EXPLORING: emit_node for what you learned. Cap = 5/turn.
   PRIORITIZE: decision (non-obvious choices), invariant (must-hold
   properties), gotcha (silent failure modes). File / symbol / flow
   only if non-obvious.
4. CAPTURE RELATIONSHIPS: link(from, to, kind). Kinds: imports, calls,
   depends_on (catch-all), implements, replaces, contradicts,
   derived_from, mirrors.

NEVER skip step 3 because the graph "looks empty after step 2" — that's
how it stays empty. The graph is only worth something if every agent
that explores leaves something behind.

Emit at confidence >= 0.5 only. emit_node detects collisions and returns
candidates; re-call with merge_with: <id> or force_new: { reason: "..." }.`;

/**
 * Render the project-level AGENTS.md / CLAUDE.md preamble. Wraps
 * SERVER_INSTRUCTIONS with a header (so users know where the file came from)
 * and a footer (so they know how to regenerate after upgrading codemap-mcp).
 *
 * Used by the `codemap init` CLI to seed agent-guidance files in projects
 * whose MCP client doesn't surface server.instructions (Codex Desktop as of
 * 2026-04 — see task-020 / M3a finding F1).
 */
export function agentsMdContent(projectName?: string): string {
  const heading = projectName
    ? `# ${projectName} — agent guidance (codemap)`
    : "# Agent guidance (codemap)";
  return `${heading}

This file was generated by \`codemap init\`. It tells MCP-aware agents
(Codex, Claude Code, etc.) how to use the **Codemap** MCP server attached to
this project.

Some MCP clients (e.g. Codex Desktop as of 2026-04) drop the server's
\`instructions\` field, so the lifecycle policy below is mirrored here to
guarantee the agent sees it.

---

${SERVER_INSTRUCTIONS}

---

## Why this file exists

Without it, an agent that finds the codemap MCP server will treat it as a
read-only cache: query → miss → fall back to direct exploration → done.
That leaves the graph empty forever and the next agent re-discovers the
same things from scratch. The point of codemap is the writeback loop in
step 3 above. This file tells the agent that.

## Regenerating

After \`npm i -g codemap-mcp@latest\`, regenerate this file to pick up any
lifecycle-policy updates:

\`\`\`sh
codemap init --force
\`\`\`
`;
}
